#сделать с помощью appleboy или другого env и исполняемый скрипт для очистки кеша и прочее
name: CI
on:
  push:
    branches:
    - master
jobs:
  deployment:
    name: deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: PHP 7.4
        uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '7.4'
      - name: Install Dependencies via Composer
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USER }}
          PASSWORD: ${{ secrets.SSH_PASSWORD }}
          PORT: ${{ secrets.SSH_PORT }}
        with:
          source: "."
          target: "/var/www/domains/${{ secrets.SSH_HOST }}"
          rm: true
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USER }}
          PASSWORD: ${{ secrets.SSH_PASSWORD }}
          PORT: ${{ secrets.SSH_PORT }}
          script: php ../var/www/domains/${{ secrets.SSH_HOST }}/deploy.php

